<a href="https://colab.research.google.com/github/azhar258/Advance_Data_Engineering/blob/main/Day1_03112025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
print("hello")

hello


In [98]:
print(type(10))

<class 'int'>


In [99]:
i = 10
j = 4+6
k = 2+8
l = 3+7

print(hex(id(i)))
print(hex(id(j)))
print(hex(id(k)))
print(hex(id(l)))

0xb1d608
0xb1d608
0xb1d608
0xb1d608


In [100]:
import sys
sys.version

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [101]:
# Given List
product_info1 = [101, 'pA', 1000.32, True]
print(type(product_info1))

<class 'list'>


In [102]:
print(product_info1[0])
print(product_info1[1])
print(product_info1[2])
print(product_info1[3])

101
pA
1000.32
True


In [103]:
# tuple - record
product_info2 = (101,'pA',1000.32,True) # immutable
print(type(product_info2))

<class 'tuple'>


In [104]:
product_info2

(101, 'pA', 1000.32, True)

In [105]:
product_info2[0]

101

In [106]:
product_info2[-1]

True

In [107]:
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True}
print(type(product_info3))

<class 'dict'>


In [108]:
product_info3['pid']

101

In [109]:
# list of list
product_list = [[101,'pA',1000],[102,'pB',2000],[103,'pC',3000]]
product_list


[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000]]

In [110]:
product_list.append([104, 'pD', 3450])
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000], [104, 'pD', 3450]]

In [111]:
print(product_list[0])
print(product_list[1])
print(product_list[2])
print(product_list[3])

[101, 'pA', 1000]
[102, 'pB', 2000]
[103, 'pC', 3000]
[104, 'pD', 3450]


In [112]:
print(product_list[1][0])

102


In [113]:
# list of dict
product_list = [{'pid':101,'pname':'pA','pcost':1000},
                {'pid':102,'pname':'pB','pcost':2000},
                {'pid':103,'pname':'pC','pcost':3000}
               ]


In [114]:
product_list[0]

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [115]:
product_list[0]['pname']

'pA'

In [116]:
product_list[1]['pcost']

2000

In [117]:
L = [["D1","D2","D3"],{"K1":"D4","K2":"D5"}]
L

[['D1', 'D2', 'D3'], {'K1': 'D4', 'K2': 'D5'}]

In [118]:
products = {}

products['pid'] = []
products['pname'] = []
products['pcost'] = []
products['pstatus'] = []

products


{'pid': [], 'pname': [], 'pcost': [], 'pstatus': []}

In [119]:
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1001)
products['pstatus'].append(True)

products


{'pid': [101], 'pname': ['pA'], 'pcost': [1001], 'pstatus': [True]}

In [120]:
products['pid'].append(102)
products['pname'].append('pb')
products['pcost'].append(1002)
products['pstatus'].append(False)

products

{'pid': [101, 102],
 'pname': ['pA', 'pb'],
 'pcost': [1001, 1002],
 'pstatus': [True, False]}

In [121]:
products['pid'].append(103)
products['pcost'].append(1003)
products['pname'].append('pc')
products['pstatus'].append(True)

products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pb', 'pc'],
 'pcost': [1001, 1002, 1003],
 'pstatus': [True, False, True]}

In [122]:
products={}
products['K1']={'pid':101,'pname':'pA','pcost':1000}
products['K2']={'pid':102,'pname':'pB','pcost':2000}
products['K3']={'pid':103,'pname':'pC','pcost':3000}
products['K4']={'pid':104,'pname':'pD','pcost':4000}
products

{'K1': {'pid': 101, 'pname': 'pA', 'pcost': 1000},
 'K2': {'pid': 102, 'pname': 'pB', 'pcost': 2000},
 'K3': {'pid': 103, 'pname': 'pC', 'pcost': 3000},
 'K4': {'pid': 104, 'pname': 'pD', 'pcost': 4000}}

In [123]:
products['K1']

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [124]:
products['K1']['pname']

'pA'

In [125]:
data = [
  {
    "login": "ggobi",
    "id": 423638,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==",
    "url": "https://api.github.com/orgs/ggobi",
    "repos_url": "https://api.github.com/orgs/ggobi/repos",
    "events_url": "https://api.github.com/orgs/ggobi/events",
    "hooks_url": "https://api.github.com/orgs/ggobi/hooks",
    "issues_url": "https://api.github.com/orgs/ggobi/issues",
    "members_url": "https://api.github.com/orgs/ggobi/members{/member}",
    "public_members_url": "https://api.github.com/orgs/ggobi/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/423638?v=4",
    "description": ""
  }
]

In [126]:
data[0]['login']
data[0]['url']

'https://api.github.com/orgs/ggobi'

In [127]:

L=[10,20,30,40,50]
L+100


TypeError: can only concatenate list (not "int") to list

In [128]:
import numpy
numpy.array([])

array([], dtype=float64)

In [129]:
import numpy as np
np.array([])

array([], dtype=float64)

In [130]:
arr = np.array([10,20,30,40,50])
arr+100.56

array([110.56, 120.56, 130.56, 140.56, 150.56])

In [131]:
print(arr)

[10 20 30 40 50]


In [132]:
print(arr.dtype)
print(arr.shape)

int64
(5,)


In [133]:
print(np.array([10,20,30]).dtype)
print(np.array([10,20,30.0]).dtype)
print(np.array([10,20,True]).dtype)
print(np.array([True,False]).dtype)
print(np.array([10,20,3.5,True]).dtype)
print('')
print(np.array([10,20,'data']).dtype)

int64
float64
int64
bool
float64

<U21


In [134]:
np.array([10,20,30])+100

array([110, 120, 130])

In [135]:
np.array([10,20,'data'])+100

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [136]:
np.array([10,20,30]).ndim

1

In [137]:
np.array([[10,20,30]]).ndim

2

In [138]:
arr

array([10, 20, 30, 40, 50])

In [139]:
arr = np.array([[10,20,30]])
arr.ndim

2

In [140]:
arr[0][0]

np.int64(10)

In [141]:
arr = np.array([[[10,20,30], [40,50,60]]])
print(arr.ndim, arr.shape)
print(arr)

3 (1, 2, 3)
[[[10 20 30]
  [40 50 60]]]


In [142]:
arr.reshape(3,2,1)

array([[[10],
        [20]],

       [[30],
        [40]],

       [[50],
        [60]]])

In [143]:
arr.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [144]:
L = [10,20,30,40,50]

total =0
for var in L:
  total += var
print(total)

arr1 = np.array(L)
print('from numpy', np.sum(arr1))

150
from numpy 150


In [145]:
np.mean(L)

np.float64(30.0)

In [146]:
np.median(L)

np.float64(30.0)

In [147]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))

3.5


In [148]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
np.mean(arr, axis=1)

array([2., 5.])

In [150]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [151]:
products = {'pid':[],'pname':[],'pcost':[]}
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [152]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products

{'pid': [101, 102, 103, 104],
 'pname': ['pA', 'pB', 'pC', 'pD'],
 'pcost': [1000, 2000, 3000, 4000]}

In [153]:
print(type(products))

<class 'dict'>


In [154]:
products['pcost']

[1000, 2000, 3000, 4000]

In [155]:
arr = np.array(products['pcost'])
np.sum(arr)

np.int64(10000)

In [156]:
np.max(arr)

np.int64(4000)

In [157]:
np.mean(arr)

np.float64(2500.0)

In [158]:
import pandas
pandas

<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>

In [159]:
print(pandas.Series)

<class 'pandas.core.series.Series'>


In [160]:
print(pandas.DataFrame)

<class 'pandas.core.frame.DataFrame'>


In [161]:
import pandas as pd
arr = [10,20,30,40,50]

In [162]:
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [163]:
pd.DataFrame(arr)

0
0  10
1  20
2  30
3  40
4  50

In [164]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [165]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [166]:
df1 = pd.DataFrame(products)
df1

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [167]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [168]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [169]:
df1.loc[1]


pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [170]:
df1.loc[0]

pid       101
pname      pA
pcost    1000
Name: 0, dtype: object

In [171]:
df1['pid']

0    101
1    102
2    103
Name: pid, dtype: int64

In [172]:
df1['pname']

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [173]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]

In [174]:
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pF')
products['pcost'].append(6000)

products['pid'].append(107)
products['pname'].append('pG')
products['pcost'].append(2300)

products['pid'].append(108)
products['pname'].append('pH')
products['pcost'].append(3400)

In [175]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     8 non-null      int64 
 1   pname   8 non-null      object
 2   pcost   8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes


In [176]:
df2.loc[2]

pid       103
pname      pC
pcost    3000
Name: 2, dtype: object

In [177]:
df2['pid']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
Name: pid, dtype: int64

In [178]:
df2.loc[2:]

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [179]:
df2.loc[2:5]

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000

In [180]:
df2.loc[3]['pname']

'pD'

In [181]:
df2.loc[3][['pname','pcost']]

pname      pD
pcost    4000
Name: 3, dtype: object

In [182]:
df2['pcost']
df2['pcost'] * 0.18

0     180.0
1     360.0
2     540.0
3     720.0
4     900.0
5    1080.0
6     414.0
7     612.0
Name: pcost, dtype: float64

In [183]:
df2['pcost'] > 3000

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7     True
Name: pcost, dtype: bool

In [186]:
df2[df2['pcost'] > 3000]

pid pname  pcost
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
7  108    pH   3400

In [187]:
len(df2.index)

8

In [189]:
df2.drop(3) #delecte 3rd rows

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [190]:
len(df2.index)

8

In [191]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [202]:
df3 = df2.drop(4,inplace=True)

KeyError: '[4] not found in axis'

In [203]:
len(df2.index)

7

In [205]:
print(len(df2.index))
print(len(df3.index))

7


AttributeError: 'NoneType' object has no attribute 'index'

In [206]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [207]:
df2.drop(columns='pname')

pid  pcost
0  101   1000
1  102   2000
2  103   3000
3  104   4000
5  106   6000
6  107   2300
7  108   3400

In [208]:
df2.drop(columns=['pname','pcost'])

pid
0  101
1  102
2  103
3  104
5  106
6  107
7  108

In [214]:
d = {'k1':[10,20,30,40,50], 'k2': ['d1','d2','d3','d4','d5'], 'k3': ['v1','v2','v3','v4','v5'], 'k4':[1,2,2, None, None]}
df = pd.DataFrame(d)
df

k1  k2  k3   k4
0  10  d1  v1  1.0
1  20  d2  v2  2.0
2  30  d3  v3  2.0
3  40  d4  v4  NaN
4  50  d5  v5  NaN