<a href="https://colab.research.google.com/github/azhar258/Advance_Data_Engineering/blob/main/Day1_03112025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [1]:
print(type(10))

<class 'int'>


In [4]:
i = 10
j = 4+6
k = 2+8
l = 3+7

print(hex(id(i)))
print(hex(id(j)))
print(hex(id(k)))
print(hex(id(l)))

0xb1d608
0xb1d608
0xb1d608
0xb1d608


In [5]:
import sys
sys.version

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [7]:
# Given List
product_info1 = [101, 'pA', 1000.32, True]
print(type(product_info1))

<class 'list'>


In [8]:
print(product_info1[0])
print(product_info1[1])
print(product_info1[2])
print(product_info1[3])

101
pA
1000.32
True


In [10]:
# tuple - record
product_info2 = (101,'pA',1000.32,True) # immutable
print(type(product_info2))

<class 'tuple'>


In [11]:
product_info2

(101, 'pA', 1000.32, True)

In [12]:
product_info2[0]

101

In [13]:
product_info2[-1]

True

In [14]:
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True}
print(type(product_info3))

<class 'dict'>


In [15]:
product_info3['pid']

101

In [17]:
# list of list
product_list = [[101,'pA',1000],[102,'pB',2000],[103,'pC',3000]]
product_list


[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000]]

In [18]:
product_list.append([104, 'pD', 3450])
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000], [104, 'pD', 3450]]

In [19]:
print(product_list[0])
print(product_list[1])
print(product_list[2])
print(product_list[3])

[101, 'pA', 1000]
[102, 'pB', 2000]
[103, 'pC', 3000]
[104, 'pD', 3450]


In [20]:
print(product_list[1][0])

102


In [21]:
# list of dict
product_list = [{'pid':101,'pname':'pA','pcost':1000},
                {'pid':102,'pname':'pB','pcost':2000},
                {'pid':103,'pname':'pC','pcost':3000}
               ]


In [22]:
product_list[0]

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [23]:
product_list[0]['pname']

'pA'

In [24]:
product_list[1]['pcost']

2000

In [25]:
L = [["D1","D2","D3"],{"K1":"D4","K2":"D5"}]
L

[['D1', 'D2', 'D3'], {'K1': 'D4', 'K2': 'D5'}]

In [26]:
products = {}

products['pid'] = []
products['pname'] = []
products['pcost'] = []
products['pstatus'] = []

products


{'pid': [], 'pname': [], 'pcost': [], 'pstatus': []}

In [27]:
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1001)
products['pstatus'].append(True)

products


{'pid': [101], 'pname': ['pA'], 'pcost': [1001], 'pstatus': [True]}

In [28]:
products['pid'].append(102)
products['pname'].append('pb')
products['pcost'].append(1002)
products['pstatus'].append(False)

products

{'pid': [101, 102],
 'pname': ['pA', 'pb'],
 'pcost': [1001, 1002],
 'pstatus': [True, False]}

In [29]:
products['pid'].append(103)
products['pcost'].append(1003)
products['pname'].append('pc')
products['pstatus'].append(True)

products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pb', 'pc'],
 'pcost': [1001, 1002, 1003],
 'pstatus': [True, False, True]}

In [30]:
products={}
products['K1']={'pid':101,'pname':'pA','pcost':1000}
products['K2']={'pid':102,'pname':'pB','pcost':2000}
products['K3']={'pid':103,'pname':'pC','pcost':3000}
products['K4']={'pid':104,'pname':'pD','pcost':4000}
products

{'K1': {'pid': 101, 'pname': 'pA', 'pcost': 1000},
 'K2': {'pid': 102, 'pname': 'pB', 'pcost': 2000},
 'K3': {'pid': 103, 'pname': 'pC', 'pcost': 3000},
 'K4': {'pid': 104, 'pname': 'pD', 'pcost': 4000}}

In [32]:
products['K1']

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [33]:
products['K1']['pname']

'pA'

In [35]:
data = [
  {
    "login": "ggobi",
    "id": 423638,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==",
    "url": "https://api.github.com/orgs/ggobi",
    "repos_url": "https://api.github.com/orgs/ggobi/repos",
    "events_url": "https://api.github.com/orgs/ggobi/events",
    "hooks_url": "https://api.github.com/orgs/ggobi/hooks",
    "issues_url": "https://api.github.com/orgs/ggobi/issues",
    "members_url": "https://api.github.com/orgs/ggobi/members{/member}",
    "public_members_url": "https://api.github.com/orgs/ggobi/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/423638?v=4",
    "description": ""
  }
]

In [42]:
data[0]['login']
data[0]['url']

'https://api.github.com/orgs/ggobi'

In [44]:

L=[10,20,30,40,50]
L+100


TypeError: can only concatenate list (not "int") to list

In [45]:
import numpy
numpy.array([])

array([], dtype=float64)

In [46]:
import numpy as np
np.array([])

array([], dtype=float64)

In [47]:
arr = np.array([10,20,30,40,50])
arr+100.56

array([110.56, 120.56, 130.56, 140.56, 150.56])

In [48]:
print(arr)

[10 20 30 40 50]


In [51]:
print(arr.dtype)
print(arr.shape)

int64
(5,)


In [52]:
print(np.array([10,20,30]).dtype)
print(np.array([10,20,30.0]).dtype)
print(np.array([10,20,True]).dtype)
print(np.array([True,False]).dtype)
print(np.array([10,20,3.5,True]).dtype)
print('')
print(np.array([10,20,'data']).dtype)

int64
float64
int64
bool
float64

<U21


In [53]:
np.array([10,20,30])+100

array([110, 120, 130])

In [54]:
np.array([10,20,'data'])+100

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [55]:
np.array([10,20,30]).ndim

1

In [56]:
np.array([[10,20,30]]).ndim

2

In [57]:
arr

array([10, 20, 30, 40, 50])

In [61]:
arr = np.array([[10,20,30]])
arr.ndim

2

In [62]:
arr[0][0]

np.int64(10)

In [65]:
arr = np.array([[[10,20,30], [40,50,60]]])
print(arr.ndim, arr.shape)
print(arr)

3 (1, 2, 3)
[[[10 20 30]
  [40 50 60]]]


In [67]:
arr.reshape(3,2,1)

array([[[10],
        [20]],

       [[30],
        [40]],

       [[50],
        [60]]])

In [68]:
arr.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [73]:
L = [10,20,30,40,50]

total =0
for var in L:
  total += var
print(total)

arr1 = np.array(L)
print('from numpy', np.sum(arr1))

150
from numpy 150


In [76]:
np.mean(L)

np.float64(30.0)

In [77]:
np.median(L)

np.float64(30.0)

In [79]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))

3.5


In [82]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.mean(arr, axis=1)

array([2., 5.])

In [85]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [86]:
products = {'pid':[],'pname':[],'pcost':[]}
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [88]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products

{'pid': [101, 102, 103, 104, 102, 103, 104],
 'pname': ['pA', 'pB', 'pC', 'pD', 'pB', 'pC', 'pD'],
 'pcost': [1000, 2000, 3000, 4000, 2000, 3000, 4000]}

In [89]:
print(type(products))

<class 'dict'>


In [90]:
products['pcost']

[1000, 2000, 3000, 4000, 2000, 3000, 4000]

In [91]:
arr = np.array(products['pcost'])
np.sum(arr)

np.int64(19000)

In [92]:
np.max(arr)

np.int64(4000)

In [93]:
np.mean(arr)

np.float64(2714.285714285714)

In [94]:
import pandas
pandas

<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>

In [96]:
print(pandas.Series)

<class 'pandas.core.series.Series'>


In [97]:
print(pandas.DataFrame)

<class 'pandas.core.frame.DataFrame'>


In [99]:
import pandas as pd
arr = [10,20,30,40,50]

In [100]:
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [101]:
pd.DataFrame(arr)

0
0  10
1  20
2  30
3  40
4  50

from matplotlib import pyplot as plt
_df_0[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_2[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

In [102]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [103]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [104]:
df1 = pd.DataFrame(products)
df1

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [105]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [106]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [109]:
df1.loc[1]


pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [110]:
df1.loc[0]

pid       101
pname      pA
pcost    1000
Name: 0, dtype: object

In [111]:
df1['pid']

0    101
1    102
2    103
Name: pid, dtype: int64

In [112]:
df1['pname']

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [114]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]

In [116]:
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pF')
products['pcost'].append(6000)

products['pid'].append(107)
products['pname'].append('pG')
products['pcost'].append(2300)

products['pid'].append(108)
products['pname'].append('pH')
products['pcost'].append(3400)

In [118]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     13 non-null     int64 
 1   pname   13 non-null     object
 2   pcost   13 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 444.0+ bytes


In [120]:
df2.loc[2]

pid       103
pname      pC
pcost    3000
Name: 2, dtype: object

In [119]:
df2['pid']

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     104
9     105
10    106
11    107
12    108
Name: pid, dtype: int64

In [122]:
df2.loc[2:]

pid pname  pcost
2   103    pC   3000
3   104    pD   4000
4   105    pE   5000
5   106    pF   6000
6   107    pG   2300
7   108    pH   3400
8   104    pD   4000
9   105    pE   5000
10  106    pF   6000
11  107    pG   2300
12  108    pH   3400